### ISSUE TITLE
Bug: array shape mismatch in metallicity_calculation using error prop arrays

### ISSUE THREAD

**Issue by cmccormick1** [astrochun/Metallicity_Stack_Commons#49]
The Te_pdf array created from running analysis.error_prop.fluxes_derived_prop has shape (4,1000). When passed into analysis.temp_metallicity_calc.metallicity_calculation, n_sample is incorrectly set to the length of the T_e array (4,) instead of the shape (4,1000). Array shape mismatch when trying to assign det3 (an array the length of n_sample) to T_e.

**Comment by astrochun** [comment]
Fix implemented in [`hotfix/0.9.1`](https://github.com/astrochun/Metallicity_Stack_Commons/tree/hotfix/0.9.1/Metallicity_Stack_Commons)

**Comment by astrochun** [comment]
Tested by @cmccormick1 with 704fd3f.  Closing issue.
